#!/usr/bin/env python3
"""Build the inputs tb_flip_frame.sv renders one captured game frame from.

    python sim/flip_frame_tb/make_frame.py gunbird 2700

Needs a MAME capture from scripts/mame_flip_capture.py (debug/flip/<game>/off)
and roms/<game>.zip. Writes into sim/flip_frame_tb/run/<game>_f<frame>/
(gitignored as ROM-derived):

  sprites.bin tiles.bin lut.bin   the gfx ROM regions exactly as the core's
                                  SDRAM holds them: the .mra's download stream
                                  sliced at psikyo_sdram_top.sv's region bases
  cpu_rom.bin                     a 68020 program (vasm) that writes the
                                  captured sprite RAM, palette, both VRAMs,
                                  vregs and the SH404 bank register through the
                                  real CPU bus, then parks
  board.txt                       board_gunbird board_sh404 for the testbench
  mame.png                        MAME's own snapshot of the same frame

The CPU writes the state rather than the testbench poking memories, so the
frame comes out of the production write paths (maincpu.sv decode, vreg
latches, the palette snapshot mirror, spriteram_dbuf's copy) untouched.
"""
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
VASM = REPO / "tools" / "vasm" / "vasmm68k_mot.exe"

# rtl/memory/psikyo_sdram_top.sv
SPRITES_BASE, TILES_BASE, SPRITELUT_BASE = 0x0240000, 0x0A40000, 0x1240000
SPRITES_SIZE, TILES_SIZE, SPRITELUT_SIZE = 0x800000, 0x400000, 0x040000

MRA = {"samuraia": "Samurai Aces (World).mra", "gunbird": "Gunbird (World).mra",
       "btlkroad": "Battle K-Road.mra", "s1945": "Strikers 1945 (World).mra",
       "tengai": "Tengai (World).mra"}


def zip_reader(zip_attr):
    zips = [zipfile.ZipFile(REPO / "roms" / z) for z in zip_attr.split("|")
            if (REPO / "roms" / z).exists()]
    if not zips:
        sys.exit("no zip for %s under roms/" % zip_attr)

    def read(name):
        for z in zips:
            if name in z.namelist():
                return z.read(name)
        sys.exit("part %s not found in %s" % (name, zip_attr))
    return read


def hexbytes(text):
    return bytes(int(t, 16) for t in (text or "").split())


def assemble_rom0(mra_path):
    """The .mra's <rom index="0"> download stream, by mra-tools-c's rules:
    parts concatenate in order; inside <interleave>, output byte j of each
    word takes the part's byte (map[len-1-j] - 1), and 0 skips (so map="12"
    is a pairwise swap -- docs/LESSONS_LEARNED.md)."""
    root = ET.parse(mra_path).getroot()
    rom = next(r for r in root.iter("rom") if r.get("index") == "0")
    read = zip_reader(rom.get("zip"))
    out = bytearray()
    for el in rom:
        if el.tag == "part":
            if el.get("repeat"):
                out += hexbytes(el.text) * int(el.get("repeat"), 0)
            elif el.get("name"):
                out += read(el.get("name"))
            else:
                out += hexbytes(el.text)
        elif el.tag == "interleave":
            width = int(el.get("output")) // 8
            parts = [(read(p.get("name")), p.get("map")) for p in el.findall("part")]
            pos = [0] * len(parts)
            while all(pos[i] < len(d) for i, (d, _) in enumerate(parts)):
                word = bytearray(width)
                for i, (data, m) in enumerate(parts):
                    for j in range(width):
                        digit = int(m[width - 1 - j])
                        if digit:
                            word[j] = data[pos[i] + digit - 1]
                    pos[i] += sum(1 for c in m if c != "0")
                out += word
    return bytes(out)


def board_flags(mra_path):
    """board_gunbird / board_sh404 from the mod byte, as Psikyo.sv decodes it."""
    root = ET.parse(mra_path).getroot()
    rom1 = next(r for r in root.iter("rom") if r.get("index") == "1")
    mod = hexbytes(rom1.find("part").text)[0]
    return mod & 1, (mod >> 3) & 1


LOADER = """\
; Generated by sim/flip_frame_tb/make_frame.py -- do not edit.
; Writes one captured frame's video state through the CPU bus, then parks.
        org     0
        dc.l    $00fffffc, start
        dcb.b   $400-*, 0
start:  move.w  #$2700,sr
        lea     spr_blob,a0
        lea     $400000,a1
        move.w  #$0fff,d0
.spr:   move.w  (a0)+,(a1)+
        dbra    d0,.spr
        lea     pal_blob,a0
        lea     $600000,a1
        move.w  #$0fff,d0
.pal:   move.w  (a0)+,(a1)+
        dbra    d0,.pal
        lea     vram_blob,a0
        lea     $800000,a1
        move.w  #$1fff,d0
.vram:  move.w  (a0)+,(a1)+
        dbra    d0,.vram
        lea     vregs_blob,a0
        lea     $804000,a1
        move.w  #$020f,d0
.vregs: move.w  (a0)+,(a1)+
        dbra    d0,.vregs
{bctrl}
        move.w  #$f11f,$fe0000
done:   bra.s   done
        cnop    0,2
spr_blob:   incbin "spriteram.bin"
pal_blob:   incbin "palette.bin"
vram_blob:  incbin "vram.bin"
vregs_blob: incbin "vregs_head.bin"
"""


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    game, frame = sys.argv[1], int(sys.argv[2])
    cap = REPO / "debug" / "flip" / game / "off"
    out = Path(__file__).resolve().parent / "run" / ("%s_f%05d" % (game, frame))
    out.mkdir(parents=True, exist_ok=True)
    mra = REPO / "releases" / MRA[game]

    stream = assemble_rom0(mra)
    need = SPRITELUT_BASE + SPRITELUT_SIZE
    stream = stream + b"\xFF" * max(0, need - len(stream))
    (out / "sprites.bin").write_bytes(stream[SPRITES_BASE:SPRITES_BASE + SPRITES_SIZE])
    (out / "tiles.bin").write_bytes(stream[TILES_BASE:TILES_BASE + TILES_SIZE])
    (out / "lut.bin").write_bytes(stream[SPRITELUT_BASE:SPRITELUT_BASE + SPRITELUT_SIZE])

    for region in ("spriteram", "palette", "vram"):
        shutil.copy(cap / ("f%05d_%s.bin" % (frame, region)), out / (region + ".bin"))
    vregs = (cap / ("f%05d_vregs.bin" % frame)).read_bytes()
    (out / "vregs_head.bin").write_bytes(vregs[:0x420])   # rowscroll 0x000-0x1FF, registers 0x201-0x20B

    bctrl = int((cap / ("f%05d_bctrl.txt" % frame)).read_text().strip()) \
        if (cap / ("f%05d_bctrl.txt" % frame)).exists() else -1
    bline = "        move.b  #$%02x,$c00007" % bctrl if bctrl >= 0 else "        ; no bank register write"
    (out / "loader.s").write_text(LOADER.format(bctrl=bline))
    r = subprocess.run([str(VASM), "-m68020", "-Fbin", "-quiet", "-o", "cpu_rom.bin", "loader.s"],
                       cwd=out, capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(r.stdout + r.stderr)
    rom = (out / "cpu_rom.bin").read_bytes()

    g, s = board_flags(mra)
    (out / "board.txt").write_text("%d %d\n" % (g, s))
    shutil.copy(cap / ("f%05d.png" % frame), out / "mame.png")
    print("%s: stream %d bytes, cpu_rom %d bytes, board_gunbird=%d board_sh404=%d, bctrl=%d -> %s"
          % (game, len(stream), len(rom), g, s, bctrl, out))


if __name__ == "__main__":
    main()
